# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - roel-huijskens

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_90ea6d72a8c842928595cb6b9de283b6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d6eada09f9e9433c99c7633d4a243170 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_90ea6d72a8c842928595cb6b9de283b6 }}/deroelh/personal-website:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'roel-huijskens'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_73513e14591a42b6a5dd812fc8d31816 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_90ea6d72a8c842928595cb6b9de283b6 }}/deroelh/personal-website:${{ github.sha }}'